
---
spring:
  profiles:
    active: dev
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
app:
  datasource:
    jdbc-url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

---

