

---
spring:
  profiles:
    active: dev
  thymeleaf:
    enabled: false
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
app:
  datasource:
#    jdbc-url: ${DB_URL}
#    username: ${DB_USER}
#    password: ${DB_PASS}
    #test
    jdbc-url: jdbc:postgresql://localhost:5432/turistmo
    username: "postgres"
    password: "1234qwer"
  mailgun:
    domain: ${MAILGUN_DOMAIN}
    password: ${MAILGUN_SMTP_PASSWORD}
    host: ${MAILGUN_SMTP_SERVER}
    port: ${MAILGUN_SMTP_PORT}
  site:
    url: https://turistmo.herokuapp.com/api/turistmo/confirm/
  cron:
    expression: 0 15 10 15 * ?
  secretKey: ${APP_SECRETKEY}
server:
  error:
    include-message: always

---


