export const GET_PACKAGES='GET_PACKAGES';
export const LOADING='LOADING';


export const GET_CITY_FROM_GEO_LOCATION='GET_CITY_FROM_GEO_LOCATION';

//JOAKIM WAS HERE
export const GET_PACKAGES_TRAVEL = 'GET_PACKAGES_TRAVEL';
export const GET_PACKAGES_FOOD = 'GET_PACKAGES_FOOD';
export const GET_PACKAGES_BUSINESS = 'GET_PACKAGES_BUSINESS';
export const GET_PACKAGES_CULTURE = 'GET_PACKAGES_CULTURE';
