export const LOADING='LOADING';

export const GET_CITY_FROM_GEO_LOCATION='GET_CITY_FROM_GEO_LOCATION';

export const GET_PACKAGES='GET_PACKAGES';
export const GET_PACKAGES_SUCCESS = 'GET_PACKAGES_SUCCESS';
export const GET_PACKAGES_TRAVEL = 'GET_PACKAGES_TRAVEL';
export const GET_PACKAGES_FOOD = 'GET_PACKAGES_FOOD';
export const GET_PACKAGES_BUSINESS = 'GET_PACKAGES_BUSINESS';
export const GET_PACKAGES_CULTURE = 'GET_PACKAGES_CULTURE';
export const GET_PACKAGES_FROM_CURATOR = 'GET_PACKAGES_FROM_CURATOR';


export const POST_SIGNIN_CURATOR = 'POST_SIGNIN_CURATOR';
export const POST_SIGNIN_CURATOR_SUCCESS = 'POST_SIGNIN_CURATOR_SUCCESS';
export const POST_SIGNIN_CURATOR_SUCCESS_JWT = 'POST_SIGNIN_CURATOR_SUCCESS_JWT';
export const POST_SIGNIN_CURATOR_ERROR = 'POST_SIGNIN_CURATOR_ERROR';

export const POST_PACKAGES = 'POST_PACKAGES';
export const POST_PACKAGES_ERROR = 'POST_PACKAGES_ERROR';
export const POST_PACKAGES_SUCCESS = 'POST_PACKAGES_SUCCESS';

export const POST_SIGNUP_CURATOR = 'POST_SIGNUP_CURATOR';
export const POST_SIGNUP_CURATOR_SUCCESS = 'POST_SIGNUP_CURATOR_ERROR';
export const POST_SIGNUP_CURATOR_ERROR = 'POST_SIGNUP_CURATOR_SUCCESS';

export const GET_APPLICATIONS = 'GET_APPLICATIONS';
export const GET_TAGS = 'GET_TAGS';

